// utils/shareUtils.ts

interface AgentSummary {
  name: string;
  opening: number;
  received: number;
  paid: number;
  commission: number;
  cancelled: number;
  closing: number;
}

export const shareAgentSummaryOnWhatsApp = (agent: AgentSummary): void => {
  // Format the date
  const today = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric'
  });

  // Create the message with proper Unicode emojis
  const message = `*Daily Summary - ${agent.name}*
📅 Date: ${today}

💼 *Opening Balance:* ₹${agent.opening.toLocaleString()}
📥 *Token Received:* ₹${agent.received.toLocaleString()}
💰 *Commission:* ₹${agent.commission.toLocaleString()}
📤 *Deposit Made:* ₹${agent.paid.toLocaleString()}
${agent.cancelled > 0 ? `❌ *Cancelled:* ₹${agent.cancelled.toLocaleString()}\n` : ''}
🏁 *Closing Balance:* ₹${agent.closing.toLocaleString()}

_Generated by Cash Flow Desk App_`;

  // Encode the message for URL
  const encodedMessage = encodeURIComponent(message);
  
  // Create WhatsApp URL (works on both mobile and desktop)
  const whatsappUrl = `https://wa.me/?text=${encodedMessage}`;
  
  // Open WhatsApp
  window.open(whatsappUrl, '_blank');
};